In [2]:
import numpy as np
import math
import torch

q = torch.Tensor([np.random.random(10),np.random.random(10),np.random.random(10), np.random.random(10), np.zeros((10,1)), np.zeros((10,1))])
k = torch.Tensor([np.random.random(10),np.random.random(10),np.random.random(10), np.random.random(10), np.zeros((10,1)), np.zeros((10,1))])
scores = torch.matmul(q, k.transpose(0,1)) / math.sqrt(10)
mask = torch.Tensor([1,1,1,1,0,0])
mask = mask.unsqueeze(1)
print(scores)
scores.masked_fill_(scores == 0, -np.inf)

tensor([[0.9823, 0.7815, 1.0630, 0.8885, 0.0000, 0.0000],
        [0.8904, 0.8699, 1.0279, 0.8713, 0.0000, 0.0000],
        [0.8231, 0.5911, 1.0434, 0.7836, 0.0000, 0.0000],
        [1.0006, 0.8729, 1.2090, 0.8727, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])


tensor([[0.9823, 0.7815, 1.0630, 0.8885,   -inf,   -inf],
        [0.8904, 0.8699, 1.0279, 0.8713,   -inf,   -inf],
        [0.8231, 0.5911, 1.0434, 0.7836,   -inf,   -inf],
        [1.0006, 0.8729, 1.2090, 0.8727,   -inf,   -inf],
        [  -inf,   -inf,   -inf,   -inf,   -inf,   -inf],
        [  -inf,   -inf,   -inf,   -inf,   -inf,   -inf]])

In [61]:
aa = scores.new_ones(10,1).bool()
y = torch.randn(10,1)
y.masked_fill_(~aa, 1)

tensor([[-0.1468],
        [-0.4982],
        [-0.4473],
        [-1.1490],
        [ 1.3239],
        [-0.4350],
        [-0.3972],
        [-0.2578],
        [-1.3958],
        [-0.1108]])

In [62]:
scores == 0

tensor([[False, False, False, False,  True,  True],
        [False, False, False, False,  True,  True],
        [False, False, False, False,  True,  True],
        [False, False, False, False,  True,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True]])

In [6]:
torch.ones(5,5).bool() + torch.zeros(5,5).bool()

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])