In [3]:
import torch

base = []

for _ in range(5):
    tmp = torch.randn(5,4)
    base += [tmp]

In [4]:
base

[tensor([[-1.1005, -1.8929,  0.3185, -1.5455],
         [-0.5053, -0.6224, -1.2540,  1.6279],
         [ 0.9952, -1.5557,  0.5482,  0.9010],
         [ 1.3504, -0.4804, -0.7814,  0.3560],
         [-0.4247,  0.3208,  0.1422,  0.5178]]),
 tensor([[ 1.1927, -1.2763,  0.7945,  0.8475],
         [-1.1552, -0.5199, -0.1913,  0.1046],
         [-0.4538, -0.3330, -0.1155, -0.8102],
         [-1.4197,  0.7898,  0.3152, -0.5040],
         [ 0.8286, -1.6862, -0.9211, -1.0703]]),
 tensor([[ 0.9155,  0.7450,  1.9642, -1.0627],
         [ 0.8481,  0.5197,  0.8353, -0.8859],
         [ 1.3881, -0.4900, -0.6335, -1.3896],
         [ 1.1742, -1.5228,  0.9555,  0.2449],
         [ 0.8505, -0.4094, -1.5983, -0.0100]]),
 tensor([[-0.5229,  0.5792, -1.0997, -0.9197],
         [ 0.8102,  0.7266,  0.4340,  0.1960],
         [ 2.7360, -0.4253,  0.1853, -2.2273],
         [ 0.7503, -0.6364, -0.5181, -1.3218],
         [-1.5040, -0.7679, -0.9459, -0.5997]]),
 tensor([[ 0.3070,  1.1137, -1.8400, -1.1362],
     

In [5]:
torch.stack(base) 

# stack은 list안에 있는 element들을 맨앞의 차원을 추가하고 element수 만큼 많아짐.

tensor([[[-1.1005, -1.8929,  0.3185, -1.5455],
         [-0.5053, -0.6224, -1.2540,  1.6279],
         [ 0.9952, -1.5557,  0.5482,  0.9010],
         [ 1.3504, -0.4804, -0.7814,  0.3560],
         [-0.4247,  0.3208,  0.1422,  0.5178]],

        [[ 1.1927, -1.2763,  0.7945,  0.8475],
         [-1.1552, -0.5199, -0.1913,  0.1046],
         [-0.4538, -0.3330, -0.1155, -0.8102],
         [-1.4197,  0.7898,  0.3152, -0.5040],
         [ 0.8286, -1.6862, -0.9211, -1.0703]],

        [[ 0.9155,  0.7450,  1.9642, -1.0627],
         [ 0.8481,  0.5197,  0.8353, -0.8859],
         [ 1.3881, -0.4900, -0.6335, -1.3896],
         [ 1.1742, -1.5228,  0.9555,  0.2449],
         [ 0.8505, -0.4094, -1.5983, -0.0100]],

        [[-0.5229,  0.5792, -1.0997, -0.9197],
         [ 0.8102,  0.7266,  0.4340,  0.1960],
         [ 2.7360, -0.4253,  0.1853, -2.2273],
         [ 0.7503, -0.6364, -0.5181, -1.3218],
         [-1.5040, -0.7679, -0.9459, -0.5997]],

        [[ 0.3070,  1.1137, -1.8400, -1.1362],
     

In [6]:
torch.cat(base, dim = 0)

# cat은 list안에 있는 element의 dim에다가 붙여 더한다.
# cat을 쓰면 안에 잇는 element.shape(*dim) == torch.cat 결과물

tensor([[-1.1005, -1.8929,  0.3185, -1.5455],
        [-0.5053, -0.6224, -1.2540,  1.6279],
        [ 0.9952, -1.5557,  0.5482,  0.9010],
        [ 1.3504, -0.4804, -0.7814,  0.3560],
        [-0.4247,  0.3208,  0.1422,  0.5178],
        [ 1.1927, -1.2763,  0.7945,  0.8475],
        [-1.1552, -0.5199, -0.1913,  0.1046],
        [-0.4538, -0.3330, -0.1155, -0.8102],
        [-1.4197,  0.7898,  0.3152, -0.5040],
        [ 0.8286, -1.6862, -0.9211, -1.0703],
        [ 0.9155,  0.7450,  1.9642, -1.0627],
        [ 0.8481,  0.5197,  0.8353, -0.8859],
        [ 1.3881, -0.4900, -0.6335, -1.3896],
        [ 1.1742, -1.5228,  0.9555,  0.2449],
        [ 0.8505, -0.4094, -1.5983, -0.0100],
        [-0.5229,  0.5792, -1.0997, -0.9197],
        [ 0.8102,  0.7266,  0.4340,  0.1960],
        [ 2.7360, -0.4253,  0.1853, -2.2273],
        [ 0.7503, -0.6364, -0.5181, -1.3218],
        [-1.5040, -0.7679, -0.9459, -0.5997],
        [ 0.3070,  1.1137, -1.8400, -1.1362],
        [ 0.2254,  0.7864,  0.7741