In [60]:
import numpy as np
import math

q = torch.Tensor([np.random.random(10),np.random.random(10),np.random.random(10), np.random.random(10), np.zeros((10,1)), np.zeros((10,1))])
k = torch.Tensor([np.random.random(10),np.random.random(10),np.random.random(10), np.random.random(10), np.zeros((10,1)), np.zeros((10,1))])
scores = torch.matmul(q, k.transpose(0,1)) / math.sqrt(10)
mask = torch.Tensor([1,1,1,1,0,0])
mask = mask.unsqueeze(1)
print(scores)
scores.masked_fill_(scores == 0, -np.inf)

tensor([[1.0655, 0.6862, 0.6079, 0.6621, 0.0000, 0.0000],
        [1.1476, 0.6267, 0.5015, 0.8298, 0.0000, 0.0000],
        [1.1738, 0.8736, 0.7402, 0.8658, 0.0000, 0.0000],
        [1.2497, 0.8126, 0.8301, 0.8752, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])


In [61]:
aa = scores.new_ones(10,1).bool()
y = torch.randn(10,1)
y.masked_fill_(~aa, 1)

tensor([[-0.1468],
        [-0.4982],
        [-0.4473],
        [-1.1490],
        [ 1.3239],
        [-0.4350],
        [-0.3972],
        [-0.2578],
        [-1.3958],
        [-0.1108]])

In [62]:
scores == 0

tensor([[False, False, False, False,  True,  True],
        [False, False, False, False,  True,  True],
        [False, False, False, False,  True,  True],
        [False, False, False, False,  True,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True]])